services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
    restart: unless-stopped
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - MONGO_DB=ztrack
    ports:
      - "8000:8000"
    depends_on:
      - mongo

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "5173:4173"
    environment:
      - VITE_API_URL=http://backend:8000
    depends_on:
      - backend

volumes:
  mongo_data:
